### ISSUE TITLE
How to avoid overtrading?

### ISSUE THREAD

**Issue by MRYingLEE** [notadamking/Bitcoin-Trader-RL#2]
I ran your code and found the trading (buy/sell) frequency were higher than 50%. Maybe we can think the agent is trying to explore the environment, but overtrading caused a high transaction cost and made the net worth shrank quickly.

Any discussion is welcome.

**Comment by notadamking** [comment]
We should explore new reward functions that help the agent to understand better what we want.

**Comment by notadamking** [comment]
This has been addressed during optimization.
