### ISSUE TITLE
Understanding _current_price()

### ISSUE THREAD

**Issue by JohnAllen** [notadamking/Bitcoin-Trader-RL#27]
In _current_price method in BitcoinEnvironment (sorry can’t link on mobile) we get the close value for some number of steps ahead.

 But isn’t the current price supposed to be the _current_ one at which we can buy or sell?

**Comment by notadamking** [comment]
Hey @JohnAllen, we actually start the environment `forecast_len` steps into the data frame, as our SARIMAX prediction algorithm requires at least as many input data points as output predictions. You can read more about it in #11
