### ISSUE TITLE
Trying now on Bitmex Live Market

### ISSUE THREAD

**Issue by PromediaB** [notadamking/Bitcoin-Trader-RL#29]
Hello @notadamking Im starting my test now on live market and want to ask you if the first trade is done from Bitcoin to USD or Inverse ?

As you know the Bitmex have the Buy and Sell possibility.

I only need to know if my start balance is in USD or Bitcoin ?

**Comment by notadamking** [comment]
Please paper trade, do not trade live BTC without heavily testing the algorithm first.

**Comment by notadamking** [comment]
Especially with #28 being brought to my attention, the current agent is likely to not do well on a live environment.

**Comment by PromediaB** [comment]
im only doing some test with 5 to 10 usd no more. to see how its going on the Live market.

Can you please answer to my previous question : "Need to know if my start balance is in USD or Bitcoin ?"

**Comment by notadamking** [comment]
USD.

**Comment by rhamnett** [comment]
Don't do anything at the moment, we just found a potentially major issue https://github.com/notadamking/Bitcoin-Trader-RL/issues/28

**Comment by silentrob** [comment]
https://i.imgur.com/lcxyE0D.gif

**Comment by PromediaB** [comment]
@rhamnett we are getting live data from Exchanger, the CSV was used only for training and now streaming data from Bitmex

**Comment by notadamking** [comment]
@PromediaB the trained agent will be fairly useless since it was trained on invalid data.

**Comment by PromediaB** [comment]
@notadamking Thank you for the notification, can you please do the correction on the concerned fail or just attach here what we should correct. then we will re-train the agent.

**Comment by JakubSledz** [comment]
> Hello @notadamking Im starting my test now on live market and want to ask you if the first trade is done from Bitcoin to USD or Inverse ?
> 
> As you know the Bitmex have the Buy and Sell possibility.
> 
> I only need to know if my start balance is in USD or Bitcoin ?

Hi PromediaB. Can you describe the process for using this model for live betting?

**Comment by stefintrim** [comment]
Once you had a trained model, would the following procedure work?

Set a time interval, say once per hour

Every time interval:
    get 5 days (say) of hourly (time interval-ly) data
    take an action based on trained model, observing said data, buy, sell, hodl
    log everything - incl net worth etc

**Comment by archenroot** [comment]
@PromediaB - can you share streaming connector code in your fork/branch? I would like to do such tests as well, but on other pairs, thx.

**Comment by PromediaB** [comment]
I am trying to get streaming data with Bitmex like this:
import bitmex

client = bitmex.bitmex(
    test=TEST_EXCHANGE,
    api_key=API_KEY,
    api_secret=API_SECRET
)
        ohlcv_candles = pd.DataFrame(client.Trade.Trade_getBucketed(
            binSize=self.timeframe,
            symbol='XBTUSD',
            count=100,
            reverse=True
        ).result()[0])
