### ISSUE TITLE
No agents directory will cause training to fail

### ISSUE THREAD

**Issue by mileshill** [notadamking/Bitcoin-Trader-RL#42]
https://github.com/notadamking/Bitcoin-Trader-RL/blob/5407d309526a3e3fae4f353d249aceec85b6b019/train.py#L75

FileNotFound due to AGENTS parent directory missing. 
Solution is to import os and check for the directory before saving. This solved the issues for me.

`import os
if not os.path.exists('./agents'):
    os.mkdir('./agents')
`

**Comment by rhamnett** [comment]
This has been fixed in another PR which is waiting a merge

**Comment by mileshill** [comment]
Sounds good. Great work! I've not yet been able to achieve those 850% returns yet on simulation! 
Fun challenge.
