### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by nachovoss** [notadamking/Bitcoin-Trader-RL#43]
(base) C:\Users\Nacho\Desktop\bots\Bitcoin-Trader-RL>conda install --file requirements.txt
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - statsmodels==0.10.0rc2
  - stable_baselines
  - gym
  - sklearn
  - empyrical
  - optuna
  - ta

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/win-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by rshtirmer** [comment]
The requirements file is to be installed with pip.

`pip install -r requirements.txt` should work inside your conda env

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nachovoss** [comment]
Sorry about my ignorance im new to anaconda, should i just open anaconda prompt in base  and pip install there?

**Comment by nachovoss** [comment]
That sorted it ;)
