### ISSUE TITLE
State missing when testing recurrent policy

### ISSUE THREAD

**Issue by araffin** [notadamking/Bitcoin-Trader-RL#49]
Hello,

It seems that you are not feeding the state to the LSTM policy when testing it, this can be quite problematic.
Please see [documentation](https://stable-baselines.readthedocs.io/en/master/guide/examples.html#recurrent-policies) for an example ;)

**Comment by notadamking** [comment]
Great catch. I will gladly accept a PR to fix this issue.

**Comment by notadamking** [comment]
I have fixed this. It will be included in the next version.
