### ISSUE TITLE
That line "df = df.sort_values([‘Date’])" didn’t quite work

### ISSUE THREAD

**Issue by zhenpingfeng** [notadamking/Bitcoin-Trader-RL#50]
origin link: [https://link.medium.com/4oFNMv1TxX](url)
Hmm. I got some crazy numbers (like hundreds percent). Then tried to debug your code and found that df = df.sort_values([‘Date’]) didn’t quite work for me (maybe you have some fancy pandas?) In my case it sorted dates alphabetically like

2019–05–16 02-AM
2019–05–16 02-PM
2019–05–16 03-AM
2019–05–16 03-PM

I tried simple fix (just inverted rows as they are already in order in a csv file) and then the same model started to show values like -11% and such.

But I think I should fix the trainer also and retrain the model before retesting.

**Comment by zhenpingfeng** [comment]
p.s my pandas version is 0.24.2

**Comment by arron202** [comment]
you can check issue #28[https://github.com/notadamking/Bitcoin-Trader-RL/issues/28](url)

**Comment by zhenpingfeng** [comment]
close
