### ISSUE TITLE
Performance after date-issue-fix

### ISSUE THREAD

**Issue by andre-cavalheiro** [notadamking/Bitcoin-Trader-RL#54]
So i'm a little confused with the repo right now and i'd like to understand what i'm working with since i'm not really achieving the results that were mentioned in the article.

#28 pointed out a possible problem with the data's integrity and i'd like to ask if anyone was able to recreate a profitable agent since. Although in that issue people have spoken about achieving pretty good results with the parameters that @notadamking has shared in #16 i'd like to confirm this since i was not able to replicate, all my agents fail and go into bankruptcy.

Following that question has anyone gotten to run _optimize.py_ since that same bug fix, and if so would they mind sharing the optimal parameters to avoid re-running the said script for time-saving purposes. 

I tried training my agents for 20 sessions but that didn't seem to be enough, should it?

**Comment by PromediaB** [comment]
@andre-cavalheiro Same problem here after fixing date, we are tying many thing to get it profitable back.

**Comment by robinvanleeuwen** [comment]
https://github.com/notadamking/Bitcoin-Trader-RL/issues/28#issuecomment-500973715 in #28 says he trained the agents with the same hyperparameters and got 108% profit. Offcourse we should optimize against the good dataset, but like you until now i don't get any good results.

**Comment by TheExGenesis** [comment]
Agreed. Would be good to have the following:
- Confirmation profitability is still possible;
- Suggested parameters after date fix, to try and reproduce.

**Comment by notadamking** [comment]
Let's keep the conversation in #28.
