### ISSUE TITLE
Sortino agent overtrading 

### ISSUE THREAD

**Issue by TheExGenesis** [notadamking/Bitcoin-Trader-RL#56]
The blog post suggests the Sortino reward function avoids over-trading, but on both the original and the fixed date dataset I see wild trading rates close to 50% that invariably result in a loss of more than to 50% of the starting budget. 

This is by running train.py right out of git clone. Not sure if a bug or if I'm missing something.

**Comment by TheExGenesis** [comment]
![net-worth-history-test](https://user-images.githubusercontent.com/7385326/59653766-0da54d80-91c6-11e9-9248-9c5eafe354fe.png)
Full training + test set run

**Comment by rshtirmer** [comment]
Main.py is not in this repo.. are you sure you are cloning the correct repo?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by TheExGenesis** [comment]
I meant train.py

**Comment by Ray-0403** [comment]
How about u just modify the action space to let the agent hold only one position each time and train it?

**Comment by TheExGenesis** [comment]
Thanks, I'll try that. But since this is code straight from the repo, is it possible that it's a bug? Since others have trained from scratch and achieved good results, could this be a matter of versioning of the libs?

**Comment by TheExGenesis** [comment]
Just got it to work, after yet another clean clone. Close.
