### ISSUE TITLE
Optuna

### ISSUE THREAD

**Issue by Prossi79** [notadamking/Bitcoin-Trader-RL#57]
I have done following :

-> created an environment for the Bitcoin-Trader-RL
-> run requirements
-> tried to execute optimize.py

import error -> ImportError: No module named optuna

tried to pip install Optuna, all requirements satisfied, see below.

what could be the problem?

`(Bitcoin-Trader-RL) root@vmanager6003:~/Bitcoin-Trader-RL-master# pip3 install optuna
Requirement already satisfied: optuna in /usr/local/lib/python3.6/dist-packages
Requirement already satisfied: scipy in /usr/local/lib/python3.6/dist-packages (from optuna)
Requirement already satisfied: cliff in /usr/local/lib/python3.6/dist-packages (from optuna)
Requirement already satisfied: colorlog in /usr/local/lib/python3.6/dist-packages (from optuna)
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from optuna)
Requirement already satisfied: typing in /usr/local/lib/python3.6/dist-packages (from optuna)
Requirement already satisfied: sqlalchemy>=1.1.0 in /usr/local/lib/python3.6/dist-packages (from optuna)
Requirement already satisfied: alembic in /usr/local/lib/python3.6/dist-packages (from optuna)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from optuna)
Requirement already satisfied: pandas in /usr/local/lib/python3.6/dist-packages (from optuna)
Requirement already satisfied: stevedore>=1.20.0 in /usr/local/lib/python3.6/dist-packages (from cliff->optuna)
Requirement already satisfied: pbr!=2.1.0,>=2.0.0 in /usr/local/lib/python3.6/dist-packages (from cliff->optuna)
Requirement already satisfied: PyYAML>=3.12 in /usr/lib/python3/dist-packages (from cliff->optuna)
Requirement already satisfied: PrettyTable<0.8,>=0.7.2 in /usr/local/lib/python3.6/dist-packages (from cliff->optuna)
Requirement already satisfied: cmd2!=0.8.3; python_version >= "3.0" in /usr/local/lib/python3.6/dist-packages (from cliff->optuna)
Requirement already satisfied: pyparsing>=2.1.0 in /usr/local/lib/python3.6/dist-packages (from cliff->optuna)
Requirement already satisfied: Mako in /usr/local/lib/python3.6/dist-packages (from alembic->optuna)
Requirement already satisfied: python-editor>=0.3 in /usr/local/lib/python3.6/dist-packages (from alembic->optuna)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.6/dist-packages (from alembic->optuna)
Requirement already satisfied: pytz>=2011k in /usr/local/lib/python3.6/dist-packages (from pandas->optuna)
Requirement already satisfied: pyperclip>=1.5.27 in /usr/local/lib/python3.6/dist-packages (from cmd2!=0.8.3; python_version >= "3.0"->cliff->optuna)
Requirement already satisfied: attrs>=16.3.0 in /usr/local/lib/python3.6/dist-packages (from cmd2!=0.8.3; python_version >= "3.0"->cliff->optuna)
Requirement already satisfied: colorama in /usr/local/lib/python3.6/dist-packages (from cmd2!=0.8.3; python_version >= "3.0"->cliff->optuna)
Requirement already satisfied: wcwidth>=0.1.7 in /usr/local/lib/python3.6/dist-packages (from cmd2!=0.8.3; python_version >= "3.0"->cliff->optuna)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.6/dist-packages (from Mako->alembic->optuna)
(Bitcoin-Trader-RL) root@vmanager6003:~/Bitcoin-Trader-RL-master# python ./optimize.py
Traceback (most recent call last):
  File "./optimize.py", line 11, in <module>
    import optuna
ImportError: No module named optuna
(Bitcoin-Trader-RL) root@vmanager6003:~/Bitcoin-Trader-RL-master# `

**Comment by MarkintoshZ** [comment]
You might be using different versions of python and pip

**Comment by robinvanleeuwen** [comment]
You are installing with pip3 in /usr/local/lib/python3.6/dist-packages  but you are executing 
root@vmanager6003:~/Bitcoin-Trader-RL-master# python ./optimize.py

If you also have python 2.x installed on your system, chances are that there is a symlink:
/usr/bin/python --> /usr/bin/python2  or something linke that. 

Make sure you are executing python3
