### ISSUE TITLE
[Suggestion] - Feed data from multiple exchanges

### ISSUE THREAD

**Issue by uBadRequest** [notadamking/Bitcoin-Trader-RL#60]
I believe if you feed the data from multiple exchanges into the model, it will learn to predict price movements better, based on patterns it has found in how the price change affects the other exchanges.

**Comment by mprestonise** [comment]
@uBadRequest Can you elaborate on this? How would this improve the model?

**Comment by uBadRequest** [comment]
> @uBadRequest Can you elaborate on this? How would this improve the model?

Think about what we're trying to do here, predict the price of bitcoin and make a profit. If the model can learn based off of the trading activity occurring at the same time across multiple exchanges, i'd expect a better outcome. An example might be someone dumping bitcoin on other exchanges, such as bitfinex for example, causing price fluctuation unseen on other exchanges. That exchange may have more of an influence on the actual price of bitcoin than say just what was happening on coinbase. Even during live trading, if the bot can be fed hourly price updates across all exchanges, it will discover trends unseen to the human eye. Basically predicting the future price of bitcoin based on watching activity occuring across multiple exchanges. I'm really interested to see live trading results, as i'm currently trying to implement this ... @notadamking care to shed some wisdom?

**Comment by robinvanleeuwen** [comment]
What are the hyper-parameters you are using for the testing of data? Still the ones based on the #28  error of the sorted date?

**Comment by notadamking** [comment]
Hi @uBadRequest, this is a great suggestion, and something similar has actually already been suggested in #3. I am going to close this issue in favor of keeping the conversation in one thread.
