### ISSUE TITLE
unable to render a correct graph

### ISSUE THREAD

**Issue by krowll** [notadamking/Bitcoin-Trader-RL#61]
Hi!

After changing the sorting in optimize, train and test (`df['Date'] = pd.to_datetime(df['Date'], format='%Y-%m-%d %I-%p')`), I'm unable to render a correct graph.

![image](https://user-images.githubusercontent.com/51996595/59761490-45c79180-9295-11e9-880f-715408ddf979.png)

In `BitcoinTradingGraph.py` I've changed the lines to
```
def __init__(self, df):
    self.df = df
    # self.df['Time'] = self.df['Date'].apply(
    #     lambda x: datetime.strptime(x, '%Y-%m-%d %I-%p'))
    self.df['Time'] = self.df['Date']
    self.df = self.df.sort_values('Time')
```
I've compared the dataframe with the original code and the new one and I can't find any difference. Nonetheless, I'm unable to render a correct graph.

Am I missing something here?

**Comment by rshtirmer** [comment]
You still need to add the following
`self.df[‘Time`] = self.df[‘Date’] `

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by notadamking** [comment]
This is due to #28
