### ISSUE TITLE
Curve-fitting seems to be result of high profits 

### ISSUE THREAD

**Issue by developeralgo8888** [notadamking/Bitcoin-Trader-RL#64]
The agents have been trained and fitted with same data. Marco de Prado has great book to avoid over-fitting but also use stationary synthetic data with similar distribution to train the agents

**Comment by TheExGenesis** [comment]
What do you mean? They're tested with unseen data

**Comment by TheExGenesis** [comment]
What do you mean? They're tested with unseen data

**Comment by notadamking** [comment]
This is incorrect. The agents were trained/validated/tested on separate data sets.
