### ISSUE TITLE
optimize.py error

### ISSUE THREAD

**Issue by bradley-pearson6597** [notadamking/Bitcoin-Trader-RL#65]
Attempting to run optimize.py but receving this error:
`from mpi4py import MPI`
`ImportError: DLL load failed: The specified module could not be found.`
The error seems to be stemming from tehe baselines package. Any help would be greatly appreciated.

**Comment by Connah-rs** [comment]
I had the same issue, fixed it with a system-wide installation of MPI

**Comment by bradley-pearson6597** [comment]
> I had the same issue, fixed it with a system-wide installation of MPI

Attempted to do this by deleting all elements of mpi4py and then installing again but the error still seems to be occurring. Did you go about a system-wide installation differently?

**Comment by bradley-pearson6597** [comment]
> I had the same issue, fixed it with a system-wide installation of MPI

**Comment by bradley-pearson6597** [comment]
Solved by downloading MSI from Microsoft webiste

**Comment by Ruben-E** [comment]
Had the same issue this morning on my windows machine. Apparently I had MPI version 9 installed. When I installed version 10 it worked.

Do the following:
1. Download both installers [here](https://www.microsoft.com/en-us/download/details.aspx?id=57467): `msmpisdk.msi` and `msmpisetup.exe`.
2. Install both.
3. Add the following paths to `Path` environment variable: 
- `C:\Program Files (x86)\Microsoft SDKs\MPI\Lib\x64`
- `C:\Program Files (x86)\Microsoft SDKs\MPI` (not sure if they are both needed. Just to be sure)
- `C:\Program Files\Microsoft MPI\Bin`

**Comment by bradley-pearson6597** [comment]
> Had the same issue this morning on my windows machine. Apparently I had MPI version 9 installed. When I installed version 10 it worked.
> 
> Do the following:
> 
> 1. Download both installers [here](https://www.microsoft.com/en-us/download/details.aspx?id=57467): `msmpisdk.msi` and `msmpisetup.exe`.
> 2. Install both.
> 3. Add the following paths to `Path` environment variable:
> 
> * `C:\Program Files (x86)\Microsoft SDKs\MPI\Lib\x64`
> * `C:\Program Files (x86)\Microsoft SDKs\MPI` (not sure if they are both needed. Just to be sure)
> * `C:\Program Files\Microsoft MPI\Bin`

I only needed the msmpisetup.exe in the end and that seemed to resolve the issue!

**Comment by Ruben-E** [comment]
Nice! Good to know only one is needed.

**Comment by jaggars** [comment]
same that fixed it for me as well
