### ISSUE TITLE
Commission in test enviroment

### ISSUE THREAD

**Issue by nachovoss** [notadamking/Bitcoin-Trader-RL#69]
![Figure_4](https://user-images.githubusercontent.com/38444147/59981593-f1f6d880-9605-11e9-8b2e-cd3c201c42cd.png)
Hey Guys, this is more a question  than an issue, but I thought by asking it, it may sort some doubts.

In the default test environment the commission is set as follows "commission=0.0025"
my question: does that represent   0.0025/100 or 0.0025/1 ? So 0.0025% or 0.25%??
At the moment I've got some results  but is hard to tell if good or not without knowing this.

I run hundreds of simulations and the commission fee makes a huge difference in if the bot makes money or not. 
Tonight I will try the model with other coins and maybe Forex (to see how it does just out of curiosity) and start linking it with some API to start trading live with paper money.

Also, it would be good to set up a Facebook group to share ideas and results. 

;) have a great week

**Comment by notadamking** [comment]
0.0025 here represents 0.25%, as each trade is multiplied/divided by `1 + commission`, or in this case, `1.0025`.

**Comment by nachovoss** [comment]
thanks adam!
