### ISSUE TITLE
Error: `Tensor had NaN values` when trying to train

### ISSUE THREAD

**Issue by n8henrie** [notadamking/Bitcoin-Trader-RL#7]
Hello,

I'm new to RL and gym. Thanks for open sourcing this.

I've installed the dependencies and tried to run with `python main.py`, but after a while I got a crash with the error: `InvalidArgumentError (see above for traceback): Found Inf or NaN gobal norm. : Tensor had NaN values`. This happened after 83400 total_timesteps.

Did I do something wrong? My machine has a 1080ti (thought it looks like it's hardly getting used for this, not sure if I need to do additional configuration to take advantage of the GPU, I don't see anything obvious about tensorflow device placement).

Thanks for any help you can provide.

**Comment by notadamking** [comment]
This has been fixed during optimization.
