### ISSUE TITLE
How to test model on new data

### ISSUE THREAD

**Issue by JakubSledz** [notadamking/Bitcoin-Trader-RL#70]
Hello.

I have a question. How to change the attached data set to match the format of your data set and test model on this data?

[binance-ETHUSDT-1h.zip](https://github.com/notadamking/Bitcoin-Trader-RL/files/3323849/binance-ETHUSDT-1h.zip)

**Comment by georgeMuraveiAlkh** [comment]
First of all, you need to train new model. Old models was created with 'sorting bug', and this a reason why it shows such a huge profits. After that you should use '''pandas''' to change your dataset format, or chante code to fit your new format.

**Comment by notadamking** [comment]
#3 is focused on the issue of using multiple data sources. Let's keep the discussion there.
