### ISSUE TITLE
Improve documentation and bootstrapping of new agents

### ISSUE THREAD

**Issue by Kalelv45** [notadamking/Bitcoin-Trader-RL#8]
Traceback (most recent call last):
  File "/Users/XXXX/Downloads/Bitcoin-Trader-RL-master/train.py", line 15, in <module>
    storage='sqlite:///params.db')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/optuna/study.py", line 557, in load_study
    return Study(study_name=study_name, storage=storage, sampler=sampler, pruner=pruner)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/optuna/study.py", line 78, in __init__
    self.study_id = self.storage.get_study_id_from_name(study_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/optuna/storages/rdb/storage.py", line 165, in get_study_id_from_name
    study = models.StudyModel.find_or_raise_by_name(study_name, session)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/optuna/storages/rdb/models.py", line 76, in find_or_raise_by_name
    raise ValueError(NOT_FOUND_MSG)
ValueError: Record does not exist.

**Comment by litch** [comment]
It looks like you are trying to run the `train.py`file as the first "touch" of the system.  So it's erroring when it tries to load the `ppo2_calmar` study from sqlite (since it, of course, has not been created).  If you start by running the `optimize.py` (which seems to take pretty much forever), it will actually create the study.

I think that it would be helpful if this library had something like a `initialize.py` or `setup.py` that did a bit of initialization, and then let some of the "smaller" studies run.  I'm having a pretty hard time "bootstrapping" this project - it seems to have evolved in place for the most part.

**Comment by Kalelv45** [comment]
Thanks. 
Does optimize run without any problem to you?
In my terminal I have to say it gaves multiplies warning but it seems to run and create various ppo.
I think as he said it in the article that a powerfull gpu, or maybe more in parallel are needed for this to achieve certain performance.

**Comment by martinjms** [comment]
Delere the params.db from the root directory and run optimize.py first, then train.py

**Comment by notadamking** [comment]
I appreciate everyone's help answering questions here. @litch is correct in that `optimize.py` should be the entry point into the system, as this creates valid hyper-parameters to train with later. Next you should use `train.py` to train the best set of hyper-parameters on the data set, and finally use `test.py` to see the agent's profitability. 

As for the suggestions to bootstrap this library, I think that is a great idea. I am currently in the process of writing up instructions on how to use this library in its current state, but I would love some help to make it easier to get started for new users.

**Comment by litch** [comment]
Yeah I'd love to help with any bootstrap/setup/advice/instructions/reviewing/etc.  Let me know how I can help.  I'm actively trying to get this bootstrapped today and trying it on a few environments simultaneously, so if you want to coordinate in something closer to real time, lmk.

**Comment by notadamking** [comment]
I am currently updating the Readme with instructions on how to get started using the library in its current state. The next step, which is maybe where you come in @litch, is to create a single entry file that is capable of optimizing the hyper-parameters for a specific strategy, training an agent based on the best trial every `n` trials, and then testing that agent. Is this something you'd want to take on?

**Comment by notadamking** [comment]
I have updated the Readme with instructions on how to optimize/train/test agents efficiently. From here, setting up the bootstrapping around it should be fairly simple. Let me know if you have any questions @litch

**Comment by litch** [comment]
Ok - I'd love a sanity check like, "is my system working like yours"

When I run optimize.py, I wind up with lots of things like:

```

[I 2019-06-05 17:52:56,191] Finished trial#1 resulted in value: -inf. Current best value is -inf with parameters: {'cliprange': 0.2049255606268844, 'confidence_interval': 0.9887847570382823, 'ent_coef': 0.09420696909549393, 'forecast_len': 2.239639353921737, 'gamma': 0.904157956
2291685, 'lam': 0.9225136210797897, 'learning_rate': 0.27772975765040925, 'n_steps': 1884.4576428079115, 'noptepochs': 10.4267900905214}.


[I 2019-06-05 22:57:05,219] Finished trial#4 resulted in value: -inf. Current best value is -inf with parameters: {'cliprange': 0.2049255606268844, 'confidence_interval': 0.9887847570382823, 'ent_coef': 0.09420696909549393, 'forecast_len': 2.239639353921737, 'gamma': 0.904157956
2291685, 'lam': 0.9225136210797897, 'learning_rate': 0.27772975765040925, 'n_steps': 1884.4576428079115, 'noptepochs': 10.4267900905214}.
[I 2019-06-06 03:25:30,390] Finished trial#3 resulted in value: -0.0. Current best value is -inf with parameters: {'cliprange': 0.2049255606268844, 'confidence_interval': 0.9887847570382823, 'ent_coef': 0.09420696909549393, 'forecast_len': 2.239639353921737, 'gamma': 0.904157956
2291685, 'lam': 0.9225136210797897, 'learning_rate': 0.27772975765040925, 'n_steps': 1884.4576428079115, 'noptepochs': 10.4267900905214}.
[W 2019-06-06 05:27:05,581] Setting status of trial#5 as TrialState.FAIL because of the following error: LinAlgError('Non-positive-definite forecast error covariance matrix encountered at period 1',)
Traceback (most recent call last):
  File "_inversions.pyx", line 1107, in statsmodels.tsa.statespace._filters._inversions.zinverse_univariate
ZeroDivisionError: float division
```

I have never seen something where a trail output something other than fail, or "value is inf" (or maybe -inf).

And lots of those failures about NaN's in tensors, etc.

**Comment by notadamking** [comment]
1. Are you using the latest version of the repo?
2. Are you trying to test the `calmar` strategy? This strategy has been giving me lots of problems during hyper-parameter optimization, and as such I've had to just borrow hyper-parameters from other agents to test the strategy.

**Comment by litch** [comment]
Yes. Just with a clone, install requirements, then `python optimize.py`.  Lots of scary-looking output.  I think it does actually have some trials that aren’t “failures”, but it’s hard for me to tell, since I don’t really know what success would look like and am kind of trying to orient myself on a few “stacks” at once.

**Comment by litch** [comment]
It may actually be due to weird state - tried deleting all my .db files and things seem to be going without any output (which seems better than dumping errors pretty steadily) - though I don't really know that it's "going", just see a lot of cpu burn...

**Comment by notadamking** [comment]
> It may actually be due to weird state - tried deleting all my .db files and things seem to be going without any output (which seems better than dumping errors pretty steadily) - though I don't really know that it's "going", just see a lot of cpu burn...

This is to be expected. If you would like to see progressive updates, you can change `verbose=0` to `verbose=1` in the agent's initiIalization.

My daily development machine is a Mac, while the machine I do the heavy lifting (CPU/GPU) on uses Windows (for the most part). That machine does dual boot into Fedora if needed. On my Mac I do not use any environment manager, but on Windows I use `conda` for convenience.

**Comment by litch** [comment]
Ok, that is exactly what my setup is hardware-wise.  Mac laptop and then I have a windows machine with a 2070 to try heavy lifting.  I got a session to actually run after clearing my database out.  And when I had tried running it on the windows machine, thought nothing was working since the GPU was just sitting at 1-2%, but now I saw your other update, so am a bit encouraged on that front.

I *think* I have a system that's now actually working, and can think about extending it.

**Comment by notadamking** [comment]
>  I thought nothing was working since the GPU was just sitting at 1-2%

Yes, this is something I am actively trying to improve. I have experimented with using a larger policy network (more layers/more nodes), however I didn't see that much of a change since the largest bottleneck in the system is the CPU.

> I _think_ I have a system that's now actually working, and can think about extending it.

Awesome to hear. Hopefully we can make that process simpler for newcomers, so it doesn't take so long to get up and running!

**Comment by notadamking** [comment]
@litch How's it going?

**Comment by litch** [comment]
Oh!  Going ok on that from. I think I got a full session to run (saw the animated graphic when running the test.py file). 

I noticed that when I run optimize to do a lot of trials, most fail after the first 20 or so.  Lots of successes in the first 20, but now they are all FAILED or PRUNED.

Is that normal?

**Comment by notadamking** [comment]
It is normal that the prune count would increase as the optimization gets closer and closer to the optimal values, though increased failures is worrisome. Are you getting any specific errors?

**Comment by nachovoss** [comment]
hey guys im running in to this issue when running optimize.py 
all help will be apriciated!

(base) C:\Users\Nacho\Desktop\bots\Bitcoin-Trader-RL>python ./optimize.py
Traceback (most recent call last):
  File "./optimize.py", line 43, in <module>
    df = add_indicators(df.reset_index())
  File "C:\Users\Nacho\Desktop\bots\Bitcoin-Trader-RL\util\indicators.py", line 7, in add_indicators
    df["High"], df["Low"], df["Close"], df["Volume BTC"])
  File "C:\Users\Nacho\Anaconda3\lib\site-packages\ta\momentum.py", line 75, in money_flow_index
    df.loc[(df['Close'] > df['Close'].shift(1, fill_value=df['Close'].mean())), 'Up_or_Down'] = 1
TypeError: shift() got an unexpected keyword argument 'fill_value'

**Comment by ButkiewiczP** [comment]
@notadamking FWIW, I'm seeing a lot of the same behavior. The first 25 trials or so (using sortino), are about 90% successful. I've had 0 complete trials since then, most (95%) have failed with the following error:

    Setting status of trial#282 as TrialState.FAIL because of the following error: 
    LinAlgError('Non-positive-definite forecast error covariance matrix encountered at period 1',)

**Comment by notadamking** [comment]
#23 has been merged solving the majority of this issue. The only thing left to be done is improve the documentation.
